FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /payment ./cmd/payment

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /payment /payment
EXPOSE 8091
ENTRYPOINT ["/payment"]
